python bootstrap_loess.py ../data/top50.tsv "black" > ../data/ci/"black.res.txt"
python bootstrap_loess.py ../data/top50.tsv "east_asian" > ../data/ci/"east_asian.res.txt"
python bootstrap_loess.py ../data/top50.tsv "hispanic_latino" > ../data/ci/"hispanic_latino.res.txt"
python bootstrap_loess.py ../data/top50.tsv "south_asian" > ../data/ci/"south_asian.res.txt"
python bootstrap_loess.py ../data/top50.tsv "white" > ../data/ci/"white.res.txt"
python bootstrap_loess.py ../data/top50.tsv "men" > ../data/ci/"men.res.txt"
python bootstrap_loess.py ../data/top50.tsv "women" > ../data/ci/"women.res.txt"
python bootstrap_loess.py ../data/top50.tsv "entropy" > ../data/ci/"entropy.res.txt"
python bootstrap_loess.py ../data/top50.tsv "lead black" > ../data/ci/"lead black.res.txt"
python bootstrap_loess.py ../data/top50.tsv "lead east_asian" > ../data/ci/"lead east_asian.res.txt"
python bootstrap_loess.py ../data/top50.tsv "lead hispanic_latino" > ../data/ci/"lead hispanic_latino.res.txt"
python bootstrap_loess.py ../data/top50.tsv "lead south_asian" > ../data/ci/"lead south_asian.res.txt"
python bootstrap_loess.py ../data/top50.tsv "lead white" > ../data/ci/"lead white.res.txt"
python bootstrap_loess.py ../data/top50.tsv "lead men" > ../data/ci/"lead men.res.txt"
python bootstrap_loess.py ../data/top50.tsv "lead women" > ../data/ci/"lead women.res.txt"
python bootstrap_loess.py ../data/top50.tsv "non-lead black" > ../data/ci/"non-lead black.res.txt"
python bootstrap_loess.py ../data/top50.tsv "non-lead east_asian" > ../data/ci/"non-lead east_asian.res.txt"
python bootstrap_loess.py ../data/top50.tsv "non-lead hispanic_latino" > ../data/ci/"non-lead hispanic_latino.res.txt"
python bootstrap_loess.py ../data/top50.tsv "non-lead south_asian" > ../data/ci/"non-lead south_asian.res.txt"
python bootstrap_loess.py ../data/top50.tsv "non-lead white" > ../data/ci/"non-lead white.res.txt"
python bootstrap_loess.py ../data/top50.tsv "non-lead men" > ../data/ci/"non-lead men.res.txt"
python bootstrap_loess.py ../data/top50.tsv "non-lead women" > ../data/ci/"non-lead women.res.txt"

python bootstrap_loess.py ../data/awards.tsv "black" > ../data/ci/black.awards.res.txt